### ISSUE TITLE
Does not like SSL connections? smap0: discarding oversize frame (len=1526) 

### ISSUE THREAD

**Issue by VTSTech** [TheLastRar/CLR-DEV9#11]
Does not like SSL connections? smap0: discarding oversize frame (len=1526) 

This was in Call of Duty 3. SLUS_214.26

CLR_DEV9:Winsock Information: 8 : Creating New TCP Connection with Dest Port 443
CLR_DEV9:SMAP Information: 4 : wSMAP
CLR_DEV9:SMAP Information: 4 : rSMAP
smap0: discarding oversize frame (len=1526)
CLR_DEV9:Winsock Information: 8 : Closed Dead Connection
CLR_DEV9:Winsock Information: 8 : Closed Dead Connection

**Comment by TheLastRar** [comment]
This has been fixed in development, but has not yet been included on any releases.

I should have a windows build out later today that includes the fix

**Comment by TheLastRar** [comment]
This should be fixed in v0.8.5

See https://forums.pcsx2.net/Thread-Experimental-Winsock-based-DEV9-plugin-Now-with-HDD-Support
