### ISSUE TITLE
Opening UDP port freezes the emulator

### ISSUE THREAD

**Issue by kylemiller3** [TheLastRar/CLR-DEV9#12]
Tried: Timesplitters 2, Midnight Club 3 Dub Remix on Ubuntu 18.04

Troubleshooting I did:
Removed old version
Used latest build of CLR-DEV9 on this git with settings that worked before.
Used debug version I built from source after cleaning and resetting git
Used v0.8.5 on both latest nightly build and 1.4.0
Used nulldev9

Results:
Midnight club black screens and I have to kill the process.
Timesplitters 2 loads about 75% of the way then freezes.
Games run fine if using nulldev9

Log of TS2:
```
loadmodule: fname cdrom0:¥MODULES¥DEV9.IRX;1 args 0 arg 
dev9: CXD9611 detected.
CLR_DEV9:SMAP Information: 4 : BD byteswapping enabled
CLR_DEV9:SMAP Error: 4 : SMAP_R_EMAC3_TxMODE1 32bit write 380F0000
CLR_DEV9:SMAP Error: 4 : Adapter Detection Hack - Resetting RX/TX
dev9: Speed chip: ES2
RegisterIntrHandler: intr INT_PCMCIA, handler b8514
RegisterLibraryEntries:     dev9
dev9: CXD9611(ssbus buffer) driver start
loadmodule: id 33, ret 0
Set GS CRTC configuration. Interlace Interlaced. Field Type FRAME. Mode NTSC 640x448 @ 59.940 (59.82)
RegisterIntrHandler: intr INT_dmaSPU, handler 8e3f8
RegisterIntrHandler: intr INT_dmaSPU2, handler 8e3f8
RegisterIntrHandler: intr INT_SPU, handler 8fb20
RegisterIntrHandler: intr INT_RTC4, handler 86a8
microVU1: Cached Prog = [000] [PC=3d60] [List=01] (Cache=0.000%) [0.0mb]
microVU1: Cached Prog = [001] [PC=3fd0] [List=01] (Cache=0.001%) [0.0mb]
microVU1: Cached Prog = [002] [PC=3d20] [List=01] (Cache=0.003%) [0.0mb]
microVU1: Cached Prog = [003] [PC=3da0] [List=01] (Cache=0.004%) [0.0mb]
microVU1: Cached Prog = [004] [PC=2cb0] [List=01] (Cache=0.005%) [0.0mb]
>>>ERROR: SOUND_FreeALLFileIDs
No Files stored
```

**Comment by kylemiller3** [comment]
So this is weird I must have messed up something on my end because the previous version does not work now either. I'll get back to you.

**Comment by kylemiller3** [comment]
So I just did a clean install of pcsx2 and its dependencies and I still cannot get it to work. TS2 gets a slight bit further before freezing on 0.8.4 now but still freezes. Network disk freezes as well. Midnight club still freezes. I'm not really sure what I could have done to cause it. ldd still shows all dependencies are satisfied.

**Comment by kylemiller3** [comment]
Gigahertz dev 9 driver does not freeze my emulator.

**Comment by kylemiller3** [comment]
0.8.4 commit I built 31284c2ab57e4800ea2b3a719abf0fbc2ea3e1d5

**Comment by TheLastRar** [comment]
Can you try rebuilding with the latest commit

**Comment by kylemiller3** [comment]
New commit did not fix the issue. However, I did find out what causes this freeze. When I disable incoming ports UDP 3658 in the config the games work just like normal. Checking enable causes the freeze once again.

**Comment by TheLastRar** [comment]
I think I've reproduce it (or a similar issue)

It seems an update to mono is causing issues, I'm currently still investigation.

**Comment by TheLastRar** [comment]
As a possible workaround, launch PCSX2 with MONO_THREADS_SUSPEND=preemptive

**Comment by kylemiller3** [comment]
The workaround works.
