### ISSUE TITLE
ubuntu 19.04 - crash on load

### ISSUE THREAD

**Issue by mentaluproar** [TheLastRar/CLR-DEV9#15]
I get and error when I try to load the plugin stating it has insufficient memory or resources.  All the dependencies are installed.  Below is what the pcsx2 console shows:

Loading plugins from /usr/lib/i386-linux-gnu/pcsx2...
	Bound   GS: libGSdx-AVX2.so [GSdx (GCC 8.2.0 AVX2/AVX2) 1.1.0]
	Bound  PAD: libonepad.so [OnePAD 0 2.0.0]
	Bound SPU2: libspu2x-2.0.0.so [SPU2-X 2.0.0]
	Bound CDVD: libCDVDnull.so [CDVDnull Driver 0 0.6.0]
	Bound  USB: libUSBnull-0.7.0.so [USBnull Driver 0 0.7.0]
	Bound   FW: libFWnull-0.7.0.so [FWnull Driver 0 0.7.0]
Init Mono Runtime
Close Mono Runtime
Init Mono Runtime
Close Mono Runtime
	Bound DEV9: libCLR_DEV9_LINUX_MONO.so [CLR DEV9 0.8.5]
Plugins loaded successfully.

Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Init Mono Runtime
Loaded Plugin
Unexpected end of file.
  at System.Xml.EncodingStreamWrapper.ReadBOMEncoding (System.Boolean notOutOfBand) [0x00048] in <9bd40f305da74e1cad6db77e76f875e5>:0 
  at System.Xml.EncodingStreamWrapper..ctor (System.IO.Stream stream, System.Text.Encoding encoding) [0x0002c] in <9bd40f305da74e1cad6db77e76f875e5>:0 
  at (wrapper remoting-invoke-with-check) System.Xml.EncodingStreamWrapper..ctor(System.IO.Stream,System.Text.Encoding)
  at System.Xml.XmlUTF8TextReader.SetInput (System.IO.Stream stream, System.Text.Encoding encoding, System.Xml.XmlDictionaryReaderQuotas quotas, System.Xml.OnXmlDictionaryReaderClose onClose) [0x00017] in <9bd40f305da74e1cad6db77e76f875e5>:0 
  at System.Xml.XmlDictionaryReader.CreateTextReader (System.IO.Stream stream, System.Text.Encoding encoding, System.Xml.XmlDictionaryReaderQuotas quotas, System.Xml.OnXmlDictionaryReaderClose onClose) [0x00005] in <9bd40f305da74e1cad6db77e76f875e5>:0 
  at System.Xml.XmlDictionaryReader.CreateTextReader (System.IO.Stream stream, System.Xml.XmlDictionaryReaderQuotas quotas) [0x00000] in <9bd40f305da74e1cad6db77e76f875e5>:0 
  at System.Runtime.Serialization.XmlObjectSerializer.ReadObject (System.IO.Stream stream) [0x00012] in <9bd40f305da74e1cad6db77e76f875e5>:0 
  at CLRDEV9.Config.ConfigFile.LoadConf (System.String iniFolderPath, System.String iniFileName) [0x0006c] in <22684b39bc814564b59f65387e6e42ec>:0 
  at CLRDEV9.CLR_DEV9.Init () [0x00005] in <22684b39bc814564b59f65387e6e42ec>:0 
InnitError

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeEngine' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeWin32Classic' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.KnownColors' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libgdiplus.so
  at (wrapper managed-to-native) System.Drawing.GDIPlus.GdiplusStartup(ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
  at System.Drawing.GDIPlus..cctor () [0x000b0] in <0e7ef49abb0f41ecae1af74ecc41279a>:0 
   --- End of inner exception stack trace ---
  at System.Drawing.KnownColors..cctor () [0x0001a] in <0e7ef49abb0f41ecae1af74ecc41279a>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at System.Drawing.Color.FromKnownColor (System.Drawing.KnownColor color) [0x00007] in <0e7ef49abb0f41ecae1af74ecc41279a>:0 
  at System.Drawing.Color.get_Black () [0x00000] in <0e7ef49abb0f41ecae1af74ecc41279a>:0 
  at System.Windows.Forms.ThemeWin32Classic..cctor () [0x00000] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
   --- End of inner exception stack trace ---
  at System.Windows.Forms.ThemeEngine..cctor () [0x00012] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
   --- End of inner exception stack trace ---
  at System.Windows.Forms.SystemInformation.get_MenuAccessKeysUnderlined () [0x00000] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Windows.Forms.Control..ctor () [0x000d6] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control..ctor()
  at System.Windows.Forms.WindowsFormsSynchronizationContext..cctor () [0x00000] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
   --- End of inner exception stack trace ---
  at System.Windows.Forms.Control..ctor () [0x0000d] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Windows.Forms.ScrollableControl..ctor () [0x00000] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Windows.Forms.ContainerControl..ctor () [0x0000e] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Windows.Forms.Form..ctor () [0x00012] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Windows.Forms.MessageBox+MessageBoxForm..ctor (System.Windows.Forms.IWin32Window owner, System.String text, System.String caption, System.Windows.Forms.MessageBoxButtons buttons, System.Windows.Forms.MessageBoxIcon icon, System.Boolean displayHelpButton) [0x0000c] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Windows.Forms.MessageBox+MessageBoxForm..ctor (System.Windows.Forms.IWin32Window owner, System.String text, System.String caption, System.Windows.Forms.MessageBoxButtons buttons, System.Windows.Forms.MessageBoxIcon icon) [0x00000] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.MessageBox+MessageBoxForm..ctor(System.Windows.Forms.IWin32Window,string,string,System.Windows.Forms.MessageBoxButtons,System.Windows.Forms.MessageBoxIcon)
  at System.Windows.Forms.MessageBox.Show (System.String text) [0x00000] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at PSE.CLR_PSE_PluginLog.MsgBoxErrorTrapper (System.Exception e) [0x0003b] in <22684b39bc814564b59f65387e6e42ec>:0 
  at CLRDEV9.CLR_DEV9.Log_Fatal (System.Exception ex) [0x00000] in <22684b39bc814564b59f65387e6e42ec>:0 
  at CLRDEV9.CLR_DEV9.Init () [0x0004e] in <22684b39bc814564b59f65387e6e42ec>:0 
  at PSE.CLR_PSE_DEV9.DEV9init () [0x00000] in <22684b39bc814564b59f65387e6e42ec>:0 
  at (wrapper native-to-managed) PSE.CLR_PSE_DEV9.DEV9init(System.Exception&)

**Comment by TheLastRar** [comment]
There seems to be issues reading the config file.
In your PCSX2 confilg folder, find "CLR_DEV9.ini" and post it here.

Secondly, there appears to be issues loading libgdiplus, can you verify that the file "/usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libgdiplus.so" exists.
If the file exists, can you run "ldd /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libgdiplus.so" and post the resulting output

**Comment by mentaluproar** [comment]
The ini file is empty.  I can't get it to let me configure it.
The gdiplus file is present.

**Comment by TheLastRar** [comment]
The plugin will create a ini file on load and populate it with default settings, the file shouldn't be blank.
Why it created a blank file, I don't know

Can you delete the ini file, try loading the plugin again and post the resulting stacktrace, it might tell me why the file was created blank.



Also, can you run the command `ldd /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libgdiplus.so` and post the result.

**Comment by mentaluproar** [comment]
Your command showed missing libexif and libgif.  I had to install libgif7:i386 and libexif12:i386.  It crashed again, but after deleting the blank ini, I was able to load the plugin and have it properly create a new ini.

thanks.

**Comment by mentaluproar** [comment]
other strange behavior.  You must use the null driver and do a full bios boot first.  Set the time zone, open the network utility and format the card.  Shutdown, activate your plugin, THEN it will work without crashing at boot.

Not doing this locks the whole system.

EDIT:  Nope, it just let it boot farther.  It still locks PCSX2 and you cant close it without logging out.
Last bit of info I can get from the console:
CLR_DEV9:SMAP Information: 4 : BD byteswapping enabled
CLR_DEV9:SMAP Error: 4 : SMAP_R_EMAC3_TxMODE1 32bit write 380F0000
CLR_DEV9:SMAP Error: 4 : Adapter Detection Hack - Resetting RX/TX

How do I generate that trace?

**Comment by mentaluproar** [comment]
I think I got stacktrace figured out.  If your plugin is active, the system boots, then after a few seconds freezes.  No errors in console.
```
> [New LWP 14455]
> [New LWP 14456]
> [New LWP 14457]
> [New LWP 14460]
> [New LWP 14462]
> [New LWP 14463]
> [New LWP 14552]
> [New LWP 14553]
> [New LWP 14554]
> [New LWP 14555]
> [New LWP 14556]
> [New LWP 14557]
> [New LWP 14558]
> [New LWP 14559]
> [New LWP 14560]
> [New LWP 14561]
> [New LWP 14564]
> [New LWP 14565]
> [New LWP 14566]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> 0xf7ed4939 in __kernel_vsyscall ()
> 
> Thread 20 (Thread 0xb8d3bb40 (LWP 14566)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b38056 in do_futex_wait.constprop () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xf6b38167 in __new_sem_wait_slow.constprop.1 () from /lib/i386-linux-gnu/libpthread.so.0
> #3  0xee606ed9 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #4  0xee5af707 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #5  0xee5c5969 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #6  0xee5c5b73 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #7  0xee5c6273 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #8  0xee5b5d78 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #9  0xee5b029c in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #10 0xeed073ce in ?? ()
> #11 0xee93cbe8 in ?? ()
> #12 0xeae1bbf0 in ?? ()
> #13 0xeae1b634 in ?? ()
> #14 0xeae1b554 in ?? ()
> #15 0xeae1ae28 in ?? ()
> #16 0xeae1a892 in ?? ()
> #17 0xeae1a635 in ?? ()
> #18 0xeae1a23b in ?? ()
> #19 0xeae19d34 in ?? ()
> #20 0xeae19c94 in ?? ()
> #21 0xeae19b88 in ?? ()
> #22 0xee0dd013 in ?? ()
> #23 0xee338828 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #24 0xee521cbc in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #25 0xee524efd in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #26 0xee550876 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #27 0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #28 0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 19 (Thread 0xb953cb40 (LWP 14565)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6a3c07c in ppoll () from /lib/i386-linux-gnu/libc.so.6
> #2  0xefd605d5 in pa_mainloop_poll () from /lib/i386-linux-gnu/libpulse.so.0
> #3  0xefd60bef in pa_mainloop_iterate () from /lib/i386-linux-gnu/libpulse.so.0
> #4  0xef459ad8 in ?? () from /lib/i386-linux-gnu/libSDL2-2.0.so.0
> #5  0xef3bc62c in ?? () from /lib/i386-linux-gnu/libSDL2-2.0.so.0
> #6  0xef40a0c6 in ?? () from /lib/i386-linux-gnu/libSDL2-2.0.so.0
> #7  0xef476c68 in ?? () from /lib/i386-linux-gnu/libSDL2-2.0.so.0
> #8  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #9  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 18 (Thread 0xec4ffb40 (LWP 14564)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6a3c07c in ppoll () from /lib/i386-linux-gnu/libc.so.6
> #2  0xefd605d5 in pa_mainloop_poll () from /lib/i386-linux-gnu/libpulse.so.0
> #3  0xefd60bef in pa_mainloop_iterate () from /lib/i386-linux-gnu/libpulse.so.0
> #4  0xefd60cac in pa_mainloop_run () from /lib/i386-linux-gnu/libpulse.so.0
> #5  0xef459cfa in ?? () from /lib/i386-linux-gnu/libSDL2-2.0.so.0
> #6  0xef40a0c6 in ?? () from /lib/i386-linux-gnu/libSDL2-2.0.so.0
> #7  0xef476c68 in ?? () from /lib/i386-linux-gnu/libSDL2-2.0.so.0
> #8  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #9  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 17 (Thread 0xe12ffb40 (LWP 14561)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b352f4 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xe92db05a in ?? () from /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so
> #3  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #4  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 16 (Thread 0xe2259b40 (LWP 14560)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b352f4 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xe92db05a in ?? () from /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so
> #3  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #4  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 15 (Thread 0xe2a5ab40 (LWP 14559)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b352f4 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xe92db05a in ?? () from /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so
> #3  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #4  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 14 (Thread 0xe325bb40 (LWP 14558)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b352f4 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xe92db05a in ?? () from /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so
> #3  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #4  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 13 (Thread 0xe3a5cb40 (LWP 14557)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b352f4 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xe92db05a in ?? () from /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so
> #3  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #4  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 12 (Thread 0xe425db40 (LWP 14556)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b352f4 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xe92db05a in ?? () from /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so
> #3  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #4  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 11 (Thread 0xe4a5eb40 (LWP 14555)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b352f4 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xe92db05a in ?? () from /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so
> #3  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #4  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 10 (Thread 0xe53a0b40 (LWP 14554)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b352f4 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xe92db05a in ?? () from /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so
> #3  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #4  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 9 (Thread 0xea289b40 (LWP 14553)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b38056 in do_futex_wait.constprop () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xf6b38167 in __new_sem_wait_slow.constprop.1 () from /lib/i386-linux-gnu/libpthread.so.0
> #3  0x569d68ba in ?? ()
> #4  0x5664a5b0 in ?? ()
> #5  0x569c4a72 in ?? ()
> #6  0x569c65b1 in ?? ()
> #7  0x569c6bda in ?? ()
> #8  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #9  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 8 (Thread 0xf05ffb40 (LWP 14552)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b38056 in do_futex_wait.constprop () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xf6b38167 in __new_sem_wait_slow.constprop.1 () from /lib/i386-linux-gnu/libpthread.so.0
> #3  0xee606a9e in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #4  0xee60ba91 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #5  0xee60bfa9 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #6  0xee60c0cc in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #7  0xee498b5b in mono_domain_set () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #8  0xeed2d25a in DEV9async () at /home/air/projects/CLR_DEV9_LINUX_MONO/DEV9.cpp:424
> #9  0x56633a79 in ?? ()
> #10 0x56661e05 in ?? ()
> #11 0x341291b7 in ?? ()
> Backtrace stopped: previous frame inner to this frame (corrupt stack?)
> 
```
> Thread 7 (Thread 0xec7b4b40 (LWP 14463)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b38056 in do_futex_wait.constprop () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xf6b38167 in __new_sem_wait_slow.constprop.1 () from /lib/i386-linux-gnu/libpthread.so.0
> #3  0xee59d993 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #4  0xee5507e3 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #5  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #6  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 6 (Thread 0xedbffb40 (LWP 14462)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b352f4 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xee5edbd7 in ?? () from /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libmonosgen-2.0.so.1
> #3  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #4  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 5 (Thread 0xf0fffb40 (LWP 14460)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b38056 in do_futex_wait.constprop () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xf6b38167 in __new_sem_wait_slow.constprop.1 () from /lib/i386-linux-gnu/libpthread.so.0
> #3  0x569d68ba in ?? ()
> #4  0x5664c9c2 in ?? ()
> #5  0x5664cf4f in ?? ()
> #6  0x569c4a72 in ?? ()
> #7  0x569c65b1 in ?? ()
> #8  0x569c6bda in ?? ()
> #9  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #10 0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 4 (Thread 0xf19ffb40 (LWP 14457)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b39087 in read () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0x5699ef33 in ?? ()
> #3  0x569c4a72 in ?? ()
> #4  0x569c65b1 in ?? ()
> #5  0x569c6bda in ?? ()
> #6  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #7  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 3 (Thread 0xf23ffb40 (LWP 14456)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b39087 in read () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0x5699ef33 in ?? ()
> #3  0x569c4a72 in ?? ()
> #4  0x569c65b1 in ?? ()
> #5  0x569c6bda in ?? ()
> #6  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #7  0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 2 (Thread 0xf2d6ab40 (LWP 14455)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6b38056 in do_futex_wait.constprop () from /lib/i386-linux-gnu/libpthread.so.0
> #2  0xf6b38167 in __new_sem_wait_slow.constprop.1 () from /lib/i386-linux-gnu/libpthread.so.0
> #3  0x569d68ba in ?? ()
> #4  0x5682059c in ?? ()
> #5  0x56820618 in ?? ()
> #6  0x569c4a72 in ?? ()
> #7  0x569c65b1 in ?? ()
> #8  0x569c6bda in ?? ()
> #9  0xf6b2f004 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
> #10 0xf6a46a16 in clone () from /lib/i386-linux-gnu/libc.so.6
> 
> Thread 1 (Thread 0xf59cba00 (LWP 14438)):
> #0  0xf7ed4939 in __kernel_vsyscall ()
> #1  0xf6a3bf9b in poll () from /lib/i386-linux-gnu/libc.so.6
> #2  0xf66858f0 in g_poll () from /lib/i386-linux-gnu/libglib-2.0.so.0
> #3  0xf6676333 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
> #4  0xf6676769 in g_main_loop_run () from /lib/i386-linux-gnu/libglib-2.0.so.0
> #5  0xf6f94615 in gtk_main () from /lib/i386-linux-gnu/libgtk-x11-2.0.so.0
> #6  0xf77ff4b5 in wxGUIEventLoop::DoRun() () from /lib/i386-linux-gnu/libwx_gtk2u_core-3.0.so.0
> #7  0xf7caa093 in wxEventLoopBase::Run() () from /lib/i386-linux-gnu/libwx_baseu-3.0.so.0
> #8  0xf7c6c351 in wxAppConsoleBase::MainLoop() () from /lib/i386-linux-gnu/libwx_baseu-3.0.so.0
> #9  0xf78c4def in wxAppBase::OnRun() () from /lib/i386-linux-gnu/libwx_gtk2u_core-3.0.so.0
> #10 0xf7cfc81a in wxEntry(int&, wchar_t**) () from /lib/i386-linux-gnu/libwx_baseu-3.0.so.0
> #11 0xf7cfd533 in wxEntry(int&, char**) () from /lib/i386-linux-gnu/libwx_baseu-3.0.so.0
> #12 0x56609a8f in ?? ()
> #13 0xf6965751 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
> #14 0x5660f393 in ?? ()
> [Inferior 1 (process 14438) detached]
>

**Comment by TheLastRar** [comment]
Can you try this version?

https://github.com/TheLastRar/CLR-DEV9/releases/tag/v0.8.6PR1

**Comment by mentaluproar** [comment]
crashes on config.  No logs. can't get a stacktrace on the process after its killed.  no error messages.

**Comment by TheLastRar** [comment]
I'll see if I can replicate it, It may be possible that 19.04 introduced a breaking change somehow. Edit: or 0.8.6 has a bug that didn't come up in my testing

**Comment by TheLastRar** [comment]
Can you try this version?

https://github.com/TheLastRar/CLR-DEV9/releases/tag/V0.8.6PR2

**Comment by mentaluproar** [comment]
Run the sony setup disc fine, except for a long delay where it tries to find the sony servers.  Good so far.

I went to try Twisted Metal Black online and had an issue.  I started up the game, went to the lan lobby, then went to another machine on my network and loaded up the game.  I created a server, then on this machine I hit "refresh list."  crash.
`Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.
  at System.Net.Sockets.UdpClient.Send (System.Byte[] dgram, System.Int32 bytes, System.Net.IPEndPoint endPoint) [0x00013] in <e8eb3d7a311640f484845e45cbec8973>:0 
  at CLRDEV9.DEV9.SMAP.Winsock.Sessions.UDPSession.Send (CLRDEV9.DEV9.SMAP.Winsock.PacketReader.IP.IPPayload payload) [0x00171] in <80711967070a4600b27d654d7ec3e091>:0 
  at CLRDEV9.DEV9.SMAP.Winsock.Winsock.SendUDP (CLRDEV9.DEV9.SMAP.Winsock.ConnectionKey Key, CLRDEV9.DEV9.SMAP.Winsock.PacketReader.IP.IPPacket ipPkt) [0x002ab] in <80711967070a4600b27d654d7ec3e091>:0 
  at CLRDEV9.DEV9.SMAP.Winsock.Winsock.SendIP (CLRDEV9.DEV9.SMAP.Winsock.PacketReader.IP.IPPacket ipPkt) [0x000c9] in <80711967070a4600b27d654d7ec3e091>:0 
  at CLRDEV9.DEV9.SMAP.Winsock.Winsock.Send (CLRDEV9.DEV9.SMAP.Data.NetPacket pkt) [0x000d9] in <80711967070a4600b27d654d7ec3e091>:0 
  at CLRDEV9.DEV9.SMAP.AdapterManager.TxPut (CLRDEV9.DEV9.SMAP.Data.NetPacket& pkt) [0x00008] in <80711967070a4600b27d654d7ec3e091>:0 
  at CLRDEV9.DEV9.SMAP.SMAP_State.TxProcess () [0x00200] in <80711967070a4600b27d654d7ec3e091>:0 
  at CLRDEV9.DEV9.SMAP.SMAP_State.EMAC3_Write (System.UInt32 addr) [0x000de] in <80711967070a4600b27d654d7ec3e091>:0 
  at CLRDEV9.DEV9.SMAP.SMAP_State.SMAP_Write16 (System.UInt32 addr, System.UInt16 value) [0x0043f] in <80711967070a4600b27d654d7ec3e091>:0 
  at CLRDEV9.DEV9.DEV9_State.DEV9_Write16 (System.UInt32 addr, System.UInt16 value) [0x0002e] in <80711967070a4600b27d654d7ec3e091>:0 
  at CLRDEV9.CLR_DEV9.DEV9write16 (System.UInt32 addr, System.UInt16 value) [0x00000] in <80711967070a4600b27d654d7ec3e091>:0 
`

**Comment by mentaluproar** [comment]
The same thing happens if I create a server and back out of it.  Even on the windows version of this plugin.

**Comment by TheLastRar** [comment]
Can you try this build (That particular bug seems to be a regression introduced in 0.8.5)

 https://github.com/TheLastRar/CLR-DEV9/releases/tag/V0.8.6PR3

**Comment by mentaluproar** [comment]
SUCCESS!  I was able to connect this over LAN to a real ps2 playing twisted metal black online.  It worked great except for a severe framerate drop, but that's apparently an AMD/linux thing and not related to your plugin.

Congrats! You found and slayed the bug!

**Comment by TheLastRar** [comment]
YAY!

Thank you for testing my builds.
