### ISSUE TITLE
Crashes in some games when going online

### ISSUE THREAD

**Issue by kaceytv** [TheLastRar/CLR-DEV9#18]
I am on a locked down university network with no wired network and have to use the winsock mode to get online with PCSX2. i have gotten onto Cristian's DNS in SWBF and NFS Underground, but whenever I attempt to go online with Midnight Club 3, this occurs: 
![image](https://user-images.githubusercontent.com/61892422/76131691-7abf7400-5fdd-11ea-92ac-2deb3d0b2ad9.png)

this only happens when in winsock mode. the other modes operate as normal, however, i cannot get online with other modes as none of the adapters work. winsock mode is the only mode that recognizes my intel wifi rather than microsoft's generic driver.

settings as follows:
![pcsx2_M9QWToZkPe](https://user-images.githubusercontent.com/61892422/76131632-3fbd4080-5fdd-11ea-9177-16ae940d7af5.png)

**Comment by TheLastRar** [comment]
Can you try this release? https://github.com/TheLastRar/CLR-DEV9/releases/tag/V0.8.7

**Comment by TheLastRar** [comment]
Assumed fixed in v0.8.8
