### ISSUE TITLE
Error on Linux Mint

### ISSUE THREAD

**Issue by Hunk4TH** [TheLastRar/CLR-DEV9#19]
Hey guys,

I'm having a problem getting this plugin to work on Mint. I keep getting this error

`The selected DEV9 plugin failed to load.

Reason DEV9 plugin failed to initialize. your system may have insufficient memory or resources needed.`

Any ideas? I'm trying everything I can think of. I'm using the latest PCSX2 nightly a btw if it helps.

**Comment by TheLastRar** [comment]
Can you post your pcsx2 log and CLR_DEV9 log files

**Comment by Hunk4TH** [comment]
Sure I hope this helps. 
[emuLog.txt](https://github.com/TheLastRar/CLR-DEV9/files/4308874/emuLog.txt)

However I couldn't find the log for CLR_DEV9 only DEV9 I found was the null one :/

**Comment by TheLastRar** [comment]
Looks like libgdiplus isn't loading due to a missing libary

Can you run the command `ldd /usr/lib/games/PCSX2/mono_i386/usr/lib/libgdiplus.so` and post the output

**Comment by Hunk4TH** [comment]
It returns with ldd: /usr/lib/games/PCSX2/mono_i386/usr/lib/libgdiplus.so: No such file or directory

Even though it appears to be there. I haven't compiled the plugin btw, I used the latest  Linux build from last year. If that helps.

**Comment by TheLastRar** [comment]
libgdiplus.so has a fair list of dependecies that it needs and the usual cause of System.DllNotFoundExceptionsis when its dependicies are missing, ldd is usefull for telling what dependency is missing in such cases

that being said, the listed libary is libc, which should already be avalible.

Random question, do you have mono (either x86 or x64) installed?, that is needed in addition to the version bundled with the plugin.

**Comment by Hunk4TH** [comment]
Yeah, I figured it had to do with missing dependcies. I totally forgot about mono so I installed mono complete. I don't get an error anymore though the emulator crashes when trying to open the plugin config which I'm guessing is normal? However I tried going online on Outbreak File 2 and it doesn't want to connect. 

Is there anyway to select my network adapter?

**Comment by TheLastRar** [comment]
The plugin config should open, can you post log files when it crashes

Edit: and also a log file for the the failed connection attempt

**Comment by Hunk4TH** [comment]
[emuLog.txt](https://github.com/TheLastRar/CLR-DEV9/files/4320418/emuLog.txt)


I hope this log helps. I'm unsure how to get the log when it fails to connect. I'm guessing my ethernet adapter isn't selected which is why it doesn't connect :/

**Comment by TheLastRar** [comment]
Run `ldd /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libgdiplus.so`
(I had given the wrong path before, this should report something)

**Comment by Hunk4TH** [comment]
`$ ldd /usr/lib/i386-linux-gnu/pcsx2/mono_i386/usr/lib/libgdiplus.so
	linux-gate.so.1 (0xf7f00000)
	libglib-2.0.so.0 => /usr/lib/i386-linux-gnu/libglib-2.0.so.0 (0xf7d33000)
	libcairo.so.2 => /usr/lib/i386-linux-gnu/libcairo.so.2 (0xf7be4000)
	libfreetype.so.6 => /usr/lib/i386-linux-gnu/libfreetype.so.6 (0xf7b27000)
	libjpeg.so.8 => /usr/lib/i386-linux-gnu/libjpeg.so.8 (0xf7ab6000)
	libtiff.so.5 => /usr/lib/i386-linux-gnu/libtiff.so.5 (0xf7a37000)
	libgif.so.7 => not found
	libpng16.so.16 => /usr/lib/i386-linux-gnu/libpng16.so.16 (0xf79fd000)
	libexif.so.12 => /usr/lib/i386-linux-gnu/libexif.so.12 (0xf79c2000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf79a3000)
	libfontconfig.so.1 => /usr/lib/i386-linux-gnu/libfontconfig.so.1 (0xf7958000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf777a000)
	libpcre.so.3 => /lib/i386-linux-gnu/libpcre.so.3 (0xf7703000)
	libpixman-1.so.0 => /usr/lib/i386-linux-gnu/libpixman-1.so.0 (0xf7654000)
	libxcb-shm.so.0 => /usr/lib/i386-linux-gnu/libxcb-shm.so.0 (0xf7650000)
	libxcb.so.1 => /usr/lib/i386-linux-gnu/libxcb.so.1 (0xf7624000)
	libxcb-render.so.0 => /usr/lib/i386-linux-gnu/libxcb-render.so.0 (0xf7615000)
	libXrender.so.1 => /usr/lib/i386-linux-gnu/libXrender.so.1 (0xf7609000)
	libX11.so.6 => /usr/lib/i386-linux-gnu/libX11.so.6 (0xf74bf000)
	libXext.so.6 => /usr/lib/i386-linux-gnu/libXext.so.6 (0xf74aa000)
	libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xf748b000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf7481000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf737d000)
	liblzma.so.5 => /lib/i386-linux-gnu/liblzma.so.5 (0xf7351000)
	libjbig.so.0 => /usr/lib/i386-linux-gnu/libjbig.so.0 (0xf7342000)
	/lib/ld-linux.so.2 (0xf7f01000)
	libexpat.so.1 => /lib/i386-linux-gnu/libexpat.so.1 (0xf7310000)
	libXau.so.6 => /usr/lib/i386-linux-gnu/libXau.so.6 (0xf730c000)
	libXdmcp.so.6 => /usr/lib/i386-linux-gnu/libXdmcp.so.6 (0xf7305000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7300000)
	libbsd.so.0 => /lib/i386-linux-gnu/libbsd.so.0 (0xf72e5000)
`

also I found the log for the DEV9 plugin 
[DEV9_CLR.log](https://github.com/TheLastRar/CLR-DEV9/files/4320439/DEV9_CLR.log)

**Comment by TheLastRar** [comment]
You are missing x86 libgif, install it with ``sudo apt-get install libgif7:i386`` and try opening the config menu again

**Comment by Hunk4TH** [comment]
Thanks man I appreciate you helping me! That did the trick for the config menu. However it still won't connected here are two more logs. Sorry if I'm being a pain :/

[DEV9_CLR.log](https://github.com/TheLastRar/CLR-DEV9/files/4320759/DEV9_CLR.log)
[emuLog.txt](https://github.com/TheLastRar/CLR-DEV9/files/4320760/emuLog.txt)

**Comment by TheLastRar** [comment]
From the logs, I'm seeing this line which strikes me as unusual `netcnf: decoding error (magic="# <Son???mmp??????????.????????@????")`

Can you try remaking your network profile (Using either the ingame network wizard or a Network Access Disc)

**Comment by Hunk4TH** [comment]
Yeah, I can try that. I'm actually using my MC from Windows so maybe that could be an issue?

**Comment by Hunk4TH** [comment]
Sorry for the late reply. I still can't get it to work even after trying to set the network up again. The game doesn't seem to see the network adapter for some reason. Maybe its a Mint issue or the version of PCSX2 I'm using.

**Comment by TheLastRar** [comment]
Can you try this build and post the DEV9_CLR.log


[libCLR_DEV9_LINUX_MONO.zip](https://github.com/TheLastRar/CLR-DEV9/files/4345344/libCLR_DEV9_LINUX_MONO.zip)

**Comment by Hunk4TH** [comment]
Sorry for the late reply again. I get the same issue with that build and also with libdev9ghzdrk-0.4 that ships with the emulator. I'm starting to think maybe it's my OS :/
[DEV9_CLR.log](https://github.com/TheLastRar/CLR-DEV9/files/4364253/DEV9_CLR.log)

**Comment by TheLastRar** [comment]
Are you using the correct build? It should report as version 0.8.7 in PCSX2's plugin selector

Also attached a new build that fixes a possible crash in my last one
[libCLR_DEV9_LINUX_MONO.zip](https://github.com/TheLastRar/CLR-DEV9/files/4368296/libCLR_DEV9_LINUX_MONO.zip)

Edit: the main difference between 0.8.6 and my last builds is additional logging into DEV9_CLR.log in hopes that I can figure out where the issue might be

**Comment by Hunk4TH** [comment]
> 
> 
> Are you using the correct build? It should report as version 0.8.7 in PCSX2's plugin selector
> 
> Also attached a new build that fixes a possible crash in my last one
> [libCLR_DEV9_LINUX_MONO.zip](https://github.com/TheLastRar/CLR-DEV9/files/4368296/libCLR_DEV9_LINUX_MONO.zip)
> 
> Edit: the main difference between 0.8.6 and my last builds is additional logging into DEV9_CLR.log in hopes that I can figure out where the issue might be

Hey, I'm so sorry for the late response! I'll have to check but I think it is the correct one. I'm thinking of moving to Pop OS and try it there as well. I'll report back though.

**Comment by Hunk4TH** [comment]
Ok I finally got the config menu to come up and I am now online! I didn't really do anything different except use pre configured memory card file from Obsrv. Before doing that I did however upgrade to Linux Mint 20.  I really appreciate you helping me! Sorry again for the huge delay in responses.
