### ISSUE TITLE
External IP and localhost not working with DNS server

### ISSUE THREAD

**Issue by Blayer98** [TheLastRar/CLR-DEV9#21]
Hi there,

Been having issues trying to get the DNS server to work with my external IP, and also localhost so I can test out a server I'm contributing to...

I've tried the following:
Adding the url of the original game's domain to hosts with localhost set (127.0.0.1) - Connection was attempted but the Console log never said it created a TCP packet (11110 is the port being used.)
Adding the url of the original game's domain to hosts with my external ip set. I had opened the port 11110 on my router and testing it worked with the server software, and the game created a TCP packet with 11110, and was connecting to my external ip, but no connection was ever made, and the server software was still running but was not getting the connection from the game.

**Comment by TheLastRar** [comment]
By default, the plugin bypasses windows name resolution and contacts your DNS server directly (meaning hosts file redirection won't work)

If you want hosts redirection to work, then you will need to change DNS1 in the plugin to ``192.0.2.1``

Regarding localhost (127.0.0.1), I don't think I handle that correctly, so you will have to instead specify your computers's IP address, additinally, you will also need to disable ``PC IP`` in the plugin config.

**Comment by TheLastRar** [comment]
127.0.0.1 should now be handled bu CLR_DEV9's internal DNS server as of V0.8.9
