### ISSUE TITLE
Exception when using intercept DHCP and TAP driver

### ISSUE THREAD

**Issue by giou** [TheLastRar/CLR-DEV9#23]
![image](https://user-images.githubusercontent.com/5844127/84044994-8f2e5680-a9a8-11ea-9cc9-68377fcf0281.png)
![image](https://user-images.githubusercontent.com/5844127/84045098-ae2ce880-a9a8-11ea-8294-1d8f2a807b29.png)

**Using tap driver and unticking Intercept DHCP works fine**

**Version 0.8.6 doesn't has this issue**

**Comment by TheLastRar** [comment]
This should be fixed in v0.8.8

Please try the latest release to confirm (And sorry for the delay)
