### ISSUE TITLE
[Suggestion] C++ and clang-format

### ISSUE THREAD

**Issue by ichee** [TheLastRar/CLR-DEV9#24]
Curious on your thoughts to change coding to C++ and clang-format.

I expressed interest in the PCSX2 team to include your plugin with the base emulator, given it's about the only one that properly supports both HDD and the network adapter.

Their only issue was it wasn't C++ or clang-formatted.

It would certainly be a nice addition if you or anyone else are able and/or willing.

Original discussion is in issue [#1841](https://github.com/PCSX2/pcsx2/issues/1841).

**Comment by TheLastRar** [comment]
Being done as part of https://github.com/TheLastRar/CLR-DEV9/issues/31

Note that the plugin will remain as C#, only the intergrated code will be C++
