### ISSUE TITLE
MAC Address

### ISSUE THREAD

**Issue by brad2192** [TheLastRar/CLR-DEV9#3]
Hello,
 I am trying to adjust the MAC Address for compatibility issues in X-Link Kai. I have compiled a distro of PCSX2 fpr SOCOM II for X-Link Kai, but it recognizes players via MAC. I have tried both solutions with the same result of the MAC Address being unchanged, Am I doing something wrong?
"
   protected byte[] virturalDHCPMAC = { 0x76, 0x6D, 0xF4, 0x63, 0x20, 0x31 };

        protected byte[] ps2MAC = { 0x76, 0x6D, 0xF4, 0x63, 0x20, 0x31 };
                                                                                                                "

**Comment by SMACK-A-BRO** [comment]
TheLastRar, if you could help brad out that would be awesome.

Thanks

**Comment by TheLastRar** [comment]
virturalDHCPMAC does not have an effect on the PS2's MAC address, it's used for something else.

I'm currently looking into providing a solution for this right now.

**Comment by SMACK-A-BRO** [comment]
Thanks man. Greatly appreciated.

**Comment by brad2192** [comment]
Thank you very much!

**Comment by brad2192** [comment]
I was trying to edit the EEPROM as well, I know the original DEV9 has a line of code to use WinPcap MAC Address to make it unique. I need it to make it unique with the TAP Adapter not from WinPcap if possible. I believe it was from here?:

u8 eeprom[] = {
	//0x6D, 0x76, 0x63, 0x61, 0x31, 0x30, 0x08, 0x01,
	0x76, 0x6D, 0x61, 0x63, 0x30, 0x31, 0x07, 0x02,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

**Comment by TheLastRar** [comment]
The initial eeprom is located here https://github.com/TheLastRar/CLR-DEV9/blob/master/CLR_DEV9/DEV9/DEV9_State_Regs.cs#L10

The 1st 6 bytes are the MAC address, with the two bytes after being a checksum.

**Comment by brad2192** [comment]
So, is this what I have to change to adjust the MAC address?

**Comment by brad2192** [comment]
I'm honestly unaware of what line you're talking about. I've edited both line and recompiled for only the second line to throw a code and the first to display the MAC as --:--:--:--:--

        //TODO Move to constants
        static byte[] initalEEPROM = {
	        //0x6D, 0x76, 0x63, 0x61, 0x31, 0x30, 0x08, 0x01
	        0x76, 0x6D, 0x61, 0x63, 0x30, 0x31, 0x07, 0x02,
	        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	        0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00,
	        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	        0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	        0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

**Comment by brad2192** [comment]
Just trying to understand how that checksum is calculated.

**Comment by brad2192** [comment]
Unable to compile new DLL

[error log.txt](https://github.com/TheLastRar/CLR-DEV9/files/1192496/error.log.txt)

**Comment by TheLastRar** [comment]
Are you compiling with VS2017? The code compiles fine for me and the lines it is erroring out in your log appear to be valid syntax.

Also, I have attached a build that generates a unique MAC in TAP (and WinPcap if you really want to use that).
This has been lightly tested, so there may be issues.
http://www.mediafire.com/file/4mznjzw3o9m94ju/CLR_DEV9_PR_AutoUniqueMac.7z

**Comment by brad2192** [comment]
it works, but X-Link will not read it still as the MAC address is not in the range of a PS2 console. To better it takes the last 4 of the MAC and converts it to decimal. 30:31 is 48.49 on the ip. The Address is calculated as
10.253.xxx.xxx with the last digits being the MAC. can you possibly make it to where it only generates the last 4 from tap? Or somehow keep it in the MAC spectrum of PS2? May I suggest 76:6D:61:63:XX:XX
X's being the values generated via TAP? That will be the only way it will work unfortunately. Thank you for your time, send me a donation link please so I can pay you!

**Comment by brad2192** [comment]
here's the link for the X-Link IP Generator we use to get on: http://www.teamxlink.co.uk/ps2assign.php
I changed the MAC address via the adapter config but still error 6 issue

**Comment by brad2192** [comment]
http://imgur.com/w28ZL8x

**Comment by TheLastRar** [comment]
Set the adapter MAC address to something like 76:6D:61:63:69:79. (I.e. the last two pairs of values have different numbers) or reset it back to what it was before and try with the build below.

If the Tap adapter and the emulated PS2 end up with the same MAC address (which happened in your case), it would cause an error 6 issue.

Also, see updated build which implements your suggestion of only modifying the last 4 digits of the MAC http://www.mediafire.com/file/u1hatmszgeqheyh/CLR_DEV9_PR_AutoUniqueMac2.7z

**Comment by brad2192** [comment]
You are seriously the best, again please post a link of a paypal or something. I seriously appreciate your work! Also, check out www.facebook.com/SOCOMUnified we're always looking for more players, average about 70 a night. NOw there will be a lot more thanks to you!

**Comment by brad2192** [comment]
Also, I'm unaware as to why the new commit is building as an .exe?

**Comment by TheLastRar** [comment]
There are a couple debug programs that I've added along the way ("DNS Test Thing" and "UPNP Test Thing"), maybe you're building those instead of the actual plug-in?

The plug-in itself should build as a dll, I've done nothing to change that and I'm not sure why it would change for you.

With regards to a donate link, I've set one up now [linked here](https://github.com/TheLastRar/CLR-DEV9/blob/master/README.md)

**Comment by TheLastRar** [comment]
Officially fixed in release v0.7.0.
