### ISSUE TITLE
Option for a dynamically allocated hdd image

### ISSUE THREAD

**Issue by vico93** [TheLastRar/CLR-DEV9#30]
Would be possible to implement this?

Instead of making the `.raw` allocate the whole specified size at creation (fixed size), it would start very small (~40kb) and according to use it will grow in size, similar to how default disk format for VM software (VirtualBox, QEMU, VMWare) does.

Thanks for this plugin!

**Comment by ichee** [comment]
You could just apply filesystem compression to the folder the HDD is stored in, or change the path of the HDD image to where the memcards are, since PCSX2 compresses that folder by default.

Using that method, a formatted 40GB image uses just over 40MB.
