### ISSUE TITLE
need dll for linux pcsx2

### ISSUE THREAD

**Issue by samuk190** [TheLastRar/CLR-DEV9#32]
I'm using linux and i tried everything to compile it seems impossible lol

**Comment by TheLastRar** [comment]
https://github.com/TheLastRar/CLR-DEV9/releases/tag/V0.8.9 includes a release for linux

The build is done for ubuntu, but does work for a selection of other distros

Please also ensure you have all the prerequisites;

mono-complete (either x86 or x64)
libcairo (x86)
libexif (x86)
libfontconfig (x86)
libfreetype (x86)
libgif (x86)
libglib (x86)
libjpeg (x86)
libpng (x86)
libtiff (x86)

**Comment by samuk190** [comment]
> https://github.com/TheLastRar/CLR-DEV9/releases/tag/V0.8.9 includes a release for linux
> 
> The build is done for ubuntu, but does work for a selection of other distros
> 
> Please also ensure you have all the prerequisites;
> 
> mono-complete (either x86 or x64)
> libcairo (x86)
> libexif (x86)
> libfontconfig (x86)
> libfreetype (x86)
> libgif (x86)
> libglib (x86)
> libjpeg (x86)
> libpng (x86)
> libtiff (x86)

Sorry, I'm using ubuntu and I tried that  release, but the pcsx2 (Both stable and unstable) didnt detect the plugin dll. (maybe im doing wrong, what i need do? download lib from release and get what built files?)
I also have all the libs u mentioned. 
The workaround to play online games is using unstable build from pcsx2 which includes gigaherz plugin by default.

It still would be amazing to make CLR9 work. By the way, obsrv.org is the best to play with it..

**Comment by TheLastRar** [comment]
Can you provide the console log when PCSX2 tries to detect plugins?

**Comment by samuk190** [comment]
> Can you provide the console log when PCSX2 tries to detect plugins?

Sorry im newbie how to debug this? I put .so file at plugin standard folder. Do i need put something else ? R: Ok I figured that need place mono at plugin folders, but there's one issue, it says I dont have resources or memory left it failed to initialize, I saw another issue and downloaded mono repo and some libs, it didnt  work yet

**Comment by samuk190** [comment]
ok it worked now ! Lol docs should be more clear about installation on linux.

-> need mono_repo (Apt install mono-complete)
-> need some lib that the other dude said but i forgot
-> restart pc after installed the libs or run pcsx2 with --console 

Thanks for the work on porting to linux, it is awesome.
