### ISSUE TITLE
x64 PCSX2 1.7.0 (Official arch repo) Problem!

### ISSUE THREAD

**Issue by samuk190** [TheLastRar/CLR-DEV9#33]
[wx] /usr/lib/pcsx2/libCLR_DEV9_LINUX_MONO.so: class ELF wrong: ELFCLASS32

How do I Fix that?

**Comment by TheLastRar** [comment]
Is the official arch repo compiled to x64 or x86?

**Comment by samuk190** [comment]
> Is the official arch repo compiled to x64 or x86?



> Is the official arch repo compiled to x64 or x86?

x64

**Comment by iguanatamer** [comment]
Yep I'm having the same issue. Tried compiling a 64bit build but crashes pcsx2 when trying to load the plugins menu.

**Comment by TheLastRar** [comment]
I've not tested x64 Linux builds, but the default compile of the plugin is x86

x64 Linux support was added in this pr https://github.com/TheLastRar/CLR-DEV9/pull/29/files, but I've not personally tested it

It is worth noting that plugin support for DEV9 will be removed very soon (if not already, it's already been removed in PCSX2 source).

**Comment by samuk190** [comment]
> I've not tested x64 Linux builds, but the default compile of the plugin is x86
> 
> x64 Linux support was added in this pr https://github.com/TheLastRar/CLR-DEV9/pull/29/files, but I've not personally tested it
> 
> It is worth noting that plugin support for DEV9 will be removed very soon (if not already, it's already been removed in PCSX2 source).

why DEV9 support would be removed? they've added giga network driver just few builds ago? 
Why in ubuntu/debian works fine maybe because arch doesnt have support to i386 (dpkg -architecture i386?)? that's what u telling me?

**Comment by samuk190** [comment]
> I've not tested x64 Linux builds, but the default compile of the plugin is x86
> 
> x64 Linux support was added in this pr https://github.com/TheLastRar/CLR-DEV9/pull/29/files, but I've not personally tested it
> 
> It is worth noting that plugin support for DEV9 will be removed very soon (if not already, it's already been removed in PCSX2 source).

Maybe its something related to versions, sadly in arch repo only nightly is available, 1.7.0 which doesnt work with other versions of plugins that I used on ubuntu, actually idk

**Comment by samuk190** [comment]
> I've not tested x64 Linux builds, but the default compile of the plugin is x86
> 
> x64 Linux support was added in this pr https://github.com/TheLastRar/CLR-DEV9/pull/29/files, but I've not personally tested it
> 
> It is worth noting that plugin support for DEV9 will be removed very soon (if not already, it's already been removed in PCSX2 source).

also you mention that was added in the PR, it does have that patch on latest release or I have to compile?

**Comment by TheLastRar** [comment]
> why DEV9 support would be removed? they've added giga network driver just few builds ago?

I'm referring to the plugin support, as of Oct 31, 2020, plugin support for DEV9 was removed, leaving the now intergrated giga network plugin as the only option for networking. I'm assuming that the arch repo will soon, if not already, update to a build that has that plugin option removed.

> also you mention that was added in the PR, it does have that patch on latest release or I have to compile?

You will have to compile a new build, and use a version of PCSX2 that still supports DEV9 plugins

**Comment by samuk190** [comment]
> > why DEV9 support would be removed? they've added giga network driver just few builds ago?
> 
> I'm referring to the plugin support, as of Oct 31, 2020, plugin support for DEV9 was removed, leaving the now intergrated giga network plugin as the only option for networking. I'm assuming that the arch repo will soon, if not already, update to a build that has that plugin option removed.
> 
> > also you mention that was added in the PR, it does have that patch on latest release or I have to compile?
> 
> You will have to compile a new build, and use a version of PCSX2 that still supports DEV9 plugins

oh ok thanks!
