### ISSUE TITLE
Built in DEV9 plugin emu crash

### ISSUE THREAD

**Issue by Hunk4TH** [TheLastRar/CLR-DEV9#35]
Figured I'd open a separate issue for you as you requested.  

Finally got around to playing around with the latest 1.7 build. I go to network and hdd settings set my network up however upon loading the game the emulator closes itself. (does it for both games I tried Outbreak file 1 and 2) I'm using Manjaro with lastest KDE Plasma desktop, default kernel, onboard ethernet. 

Anything else I can provide you with? PCSX2 was built via AUR not using any Flatpak version. Oh I'm also using a 2006 bios if that matters?

**Comment by TheLastRar** [comment]
IIRC the AUR doesn't setup the caps correctly

You will need to run ``sudo setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' <Path to PCSX2>``

Edit: you can get the path to PCSX2 by running ``which PCSX2``

**Comment by Hunk4TH** [comment]
Thank you! No more crashing now.
