### ISSUE TITLE
Winsock: UDP Binds to same port causes emulator crash.

### ISSUE THREAD

**Issue by Blackburn29** [TheLastRar/CLR-DEV9#36]
Hey guys, 

I've been working on porting more games over to our online server and ran into an issue with winsock, which I use for local testing. Amplitude, when hosting a game, attempts to create 2 UDP connections on the same port and this causes winsock to hard-crash the emulator. (If I use winPcap, it seems to work fine, however I cannot seem to connect to a local server over winpcap due to windows loopback issues).

Emulator and Plugin Versions:
- PCSX2 1.6 - CLR_DEV9 0.8.9
- PCSX2 1.4 - CLR_DEV9 0.8.9

![image](https://user-images.githubusercontent.com/1065472/102409858-586b7580-3fb5-11eb-9cef-7c5eecd14b8c.png)

If you have any more questions, please don't hesitate to ask!

-K3rber0s

**Comment by TheLastRar** [comment]
I'm currently working fixing support for this server, I've attatched an build that has a fix for that specific issue
[CLR_DEV9.zip](https://github.com/TheLastRar/CLR-DEV9/files/5708491/CLR_DEV9.zip)

**Comment by Blackburn29** [comment]
This version seems to be working much better. I seem to have issues with p2p cross-network but this might just be a NAT issue. I haven't had a chance to look into it much more since my last post. Thank for you for supplying that version Rar.

**Comment by TheLastRar** [comment]
V0.9.0 has been released containing the fix
