### ISSUE TITLE
PCSX2 Version Error

### ISSUE THREAD

**Issue by CombiAssu** [TheLastRar/CLR-DEV9#4]
Hello, I am wondering if it is possible for this plugin to work with a previous version of PCSX2 (version 1.2.1)
"The selected plugin failed to load" is what pops up if I try to use it. I am using PCSX2Dis and it would help to have an appropriate version of an dev9 plugin to use. I hope this is possible, thank you!

**Comment by TheLastRar** [comment]
Current versions of PCSX2 have an extra API call for DEV9 plugins (DEV9async(), added sometime in 1.3.1's life)

This extra call was added to fix an instability related to receiving packets with DEV9ghzdrk, CLR_DEV9 was released after this API change and requires it to function.

**Comment by CombiAssu** [comment]
Is it possible for it to load on version 1.2.1? Or is there a previous version I could use that may be compatible?

**Comment by CombiAssu** [comment]
Or could I possibly compile a version of PSX2Dis with that API call from a newer version of PCSX2. Sorry, I'm not great at this stuff but I really need a good DEV9 plugin!

**Comment by TheLastRar** [comment]
I've attempted to port PCSX2dis to the latest GIT version (Which CLR_DEV9 should work with)

Can you try this build (http://www.mediafire.com/file/joxfpg1u85se1td/pcsx2dis+1.5.0+git.exe.7z). Using the same PCSX2dis.dll from the PCSX2dis 1.2.1 build.

Edit: Double check that the build is working correctly, I'm somewhat unfamiliar with the features of PCSX2dis, so can't verify if everything works myself.

**Comment by TheLastRar** [comment]
Closing on the assumption that the PCSX2dis build I made resolves the issue

**Comment by TylerDev905** [comment]
@TheLastRar Anyway you can post the branch that you did the pcsx2dis work on. I just ported it myself but was having some issues with the dialogs not displaying correctly.

**Comment by xCENTx** [comment]
> Closing on the assumption that the PCSX2dis build I made resolves the issue

I'm having some issues running .ELF files with this build. Do you possibly have anything updated? I'm trying to go through some elfs. Also need the CLR DEV9 to work. Currently stuck getting black screens , pcsx2dis 1.2.1\

Edit: nvm i got the 1.2.1 version of pcsx2dis working with an elf. Works for now , however all the plugins and stuff being different is a pita lol. If you got time and could share another version be cool
