### ISSUE TITLE
Plugin Crashing when running Offline

### ISSUE THREAD

**Issue by jtjanecek** [TheLastRar/CLR-DEV9#41]
I'm trying to run PCSX2 while offline (I want to dev while on a flight, without internet). 

I am using port forwarding on my machine to map `192.168.100.100` -> `127.0.0.1` so that even though I'm offline, I can still work on things. 

I'm getting an error saying that the plugin cannot open a socket. I'm wondering if there's a way around this, or some setting that I'm missing?

Attached is the log and my ini.

[error_while_running_offline.txt](https://github.com/TheLastRar/CLR-DEV9/files/7671141/error_while_running_offline.txt)
[CLR_DEV9.txt](https://github.com/TheLastRar/CLR-DEV9/files/7671149/CLR_DEV9.txt)

**Comment by TheLastRar** [comment]
The plug-in will attempt to find an adapter with internet access, raising an exception when it fails to find one.

If you want to use the plug-in in such a situation, you can manually specify a network adapter
On windows you could do this from Config->DEV9->Plugin Settings
On Linux this windows can often fail to open and you may need to edit the `CLR_DEV9.ini` file

In `CLR_DEV9.ini` find the line ``<Eth>Auto</Eth>`` and change `Auto` to any adapter you want (I.e. ``<Eth>eth0</Eth>`` for Ethernet).

Note that this situation hasn't really been tested, so you may run in to issues, let me know if you do.

**Comment by jtjanecek** [comment]
Found a different solution (connecting to wifi networks without authenticating so I could have a network)
